name: "Build"

on: [push]

jobs:
  build-linux:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup GraalVM
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: '20.3.0.java11'

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.1.763'

      - name: Install native image toolchain
        run: $JAVA_HOME/bin/gu install native-image

      - name: Build native image
        run: bash script/compile

      - name: Collect Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-executable
          path: pod-stokachu-bitkit

  build-macos:
    runs-on: "macos-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup GraalVM
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: '20.3.0.java11'

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.1.763'

      - name: Install native image toolchain
        run: $JAVA_HOME/bin/gu install native-image

      - name: Build native image
        run: bash script/compile

      - name: Collect Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mac-executable
          path: pod-stokachu-bitkit
